### ISSUE TITLE
rubygems error after installing home_run in windows: `synchronize': thread 0x334f20 tried to join itself (ThreadError)

### ISSUE THREAD

**Issue by pdobb** [jeremyevans/home_run#13]
I just gem installed home_run and attempted to interact with it as per the Readme. Following is a trimmed down command history that details my problems. In the end the only way I could get my Rails environment back was to reverse the home_run --install process by hand (by deleting the copied files).

Thanks for any help with this. I'm excited to try this library out! I'm in #home_run on freenode if you want me to bounce any commands off of my environment. Thanks!

Oh and I'm running Ruby 1.8.7, Rails v2.3.9 on Windows 7. I'm also using DevKit v4.5.0: http://github.com/oneclick/rubyinstaller/wiki/Development-Kit (not sure if that matters here at all, but just in case).

C:\develop\test>ruby -v
ruby 1.8.7 (2010-08-16 patchlevel 302) [i386-mingw32]

C:\develop\test>home_run script/console
C:/Ruby187/lib/ruby/gems/1.8/gems/home_run-0.9.1-x86-mingw32/bin/home_run:87:in `exec': No such file or directory - script\console (Errno::ENOENT)
        from C:/Ruby187/lib/ruby/gems/1.8/gems/home_run-0.9.1-x86-mingw32/bin/home_run:87
        from C:/Ruby187/bin/home_run:19:in`load'
        from C:/Ruby187/bin/home_run:19

C:\develop\test>home_run --install
cp lib/date.rb C:/Ruby187/lib/ruby/site_ruby/1.8
mkdir -p C:/Ruby187/lib/ruby/site_ruby/1.8/date
cp lib/date/format.rb C:/Ruby187/lib/ruby/site_ruby/1.8/date
mkdir -p C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt/1.8
cp lib/1.8/date_ext.so C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt/1.8
mkdir -p C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt/1.9
cp lib/1.9/date_ext.so C:/Ruby187/lib/ruby/site_ruby/1.8/i386-msvcrt/1.9

C:\develop\test>ruby script/console
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `synchronize': thread 0x4394f10 tried to join itself (ThreadError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:34:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/date.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml/rubytypes.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml.rb:396
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:220:in`load_file'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:168:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in `configuration'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:635:in`path'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:68:in `installed_spec_directories'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:58:in`from_installed_gems'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:883:in `source_index'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:81:in`init_gemspecs'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:13:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`synchronize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:479:in`find_files'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:983:in `load_plugins'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1139
        from ./script/../config/boot.rb:90:in`require'
        from ./script/../config/boot.rb:90:in `load_rubygems'
        from ./script/../config/boot.rb:53:in`load_initializer'
        from ./script/../config/boot.rb:38:in `run'
        from ./script/../config/boot.rb:11:in`boot!'
        from ./script/../config/boot.rb:114
        from script/console:2:in `require'
        from script/console:2

C:\develop\test>ruby -r date -e "p Date.today"
# <Date 2010-09-12>

C:\develop\test>home_run --uninstall
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `synchronize': thread 0x2b4f10 tried to join itself (ThreadError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:34:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/date.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml/rubytypes.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml.rb:396
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:220:in`load_file'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:168:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in `configuration'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:635:in`path'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:68:in `installed_spec_directories'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:58:in`from_installed_gems'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:883:in `source_index'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:81:in`init_gemspecs'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:13:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`synchronize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:479:in`find_files'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:983:in `load_plugins'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1139
        from C:/Ruby187/bin/home_run:9:in`require'
        from C:/Ruby187/bin/home_run:9

C:\develop\test>home_run
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `synchronize': thread 0x4324f20 tried to join itself (ThreadError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:34:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/date.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml/rubytypes.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml.rb:396
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:220:in`load_file'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:168:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in `configuration'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:635:in`path'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:68:in `installed_spec_directories'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:58:in`from_installed_gems'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:883:in `source_index'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:81:in`init_gemspecs'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:13:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`synchronize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:479:in`find_files'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:983:in `load_plugins'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1139
        from C:/Ruby187/bin/home_run:9:in`require'
        from C:/Ruby187/bin/home_run:9

C:\develop\test>gem list home_run
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `synchronize': thread 0x334f20 tried to join itself (ThreadError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:34:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/date.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml/rubytypes.rb:2
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/1.8/yaml.rb:396
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:220:in`load_file'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/config_file.rb:168:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:385:in `configuration'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:635:in`path'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:68:in `installed_spec_directories'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:58:in`from_installed_gems'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:883:in `source_index'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:81:in`init_gemspecs'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/gem_path_searcher.rb:13:in `initialize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in`new'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:841:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in`synchronize'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:840:in `searcher'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:479:in`find_files'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:983:in `load_plugins'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:1139
        from C:/Ruby187/bin/gem:8:in`require'
        from C:/Ruby187/bin/gem:8

C:\develop\test>irb
irb(main):001:0> exit

**Comment by jeremyevans** [comment]
This is a bug in rubygems.  They aren't checking if the current thread already has the mutex in http://github.com/rubygems/rubygems/blob/master/lib/rubygems.rb#L840.  Either that or they aren't preventing that method from be called recursively.

They need to do something like http://github.com/jeremyevans/sequel/blob/master/lib/sequel/core.rb#L66, where they check if the current thread already has the mutex, and not use synchronize if so.

**Comment by jeremyevans** [comment]
If anyone else runs into the issue, you can work around it by either adding RUBYOPT=-rdate to your environment, or use the home_run to execute the program instead of home_run --install.

**Comment by jeremyevans** [comment]
Bug filed in rubygems bugtracker: http://rubyforge.org/tracker/index.php?func=detail&aid=28561&group_id=126&atid=575

**Comment by raggi** [comment]
Yup, I'm planning on simply removing the mutex from rubygems. It mindlessly suggests that the code base is otherwise thread safe, which is entirely untrue.

**Comment by raggi** [comment]
A performance oriented branch I have already does this.

http://github.com/rubygems/rubygems/commit/cceab040bde07d567131ccea2bc707a1f7dd7c8b
