### ISSUE TITLE
undefined method `advance' for #<Date 2010-09-13> 

### ISSUE THREAD

**Issue by jimsynz** [jeremyevans/home_run#14]
It appears that ActiveSupport on Rails3 is trying to do something that home_run doesn't support?

activesupport (3.0.0) lib/active_support/core_ext/time/calculations.rb:101:in `advance'
activesupport (3.0.0) lib/active_support/duration.rb:91:in`block in sum'
activesupport (3.0.0) lib/active_support/duration.rb:86:in `each'
activesupport (3.0.0) lib/active_support/duration.rb:86:in`inject'
activesupport (3.0.0) lib/active_support/duration.rb:86:in `sum'
activesupport (3.0.0) lib/active_support/duration.rb:62:in`since'
activesupport (3.0.0) lib/active_support/core_ext/time/calculations.rb:245:in `plus_with_duration'

**Comment by jeremyevans** [comment]
Duplicate of #12.

**Comment by jimsynz** [comment]
sorry. I did a search. should have shown up.

**Comment by jeremyevans** [comment]
Don't feel bad.  I've heard the search isn't that great. :)
