### ISSUE TITLE
Problems with spreadsheet gem

### ISSUE THREAD

**Issue by sdsykes** [jeremyevans/home_run#15]
I am using the spreadsheet gem http://spreadsheet.rubyforge.org/

Requiring it with home_run installed results in this:

/Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/types/base.rb:75:in `allocate': allocator undefined for Ole::Types::FileTime (TypeError)
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/types/base.rb:75:in`new'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/types/base.rb:88
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/types.rb:1
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/storage/base.rb:4
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/storage.rb:1
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/storage/file_system.rb:32
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/ruby-ole-1.2.10.1/lib/ole/file_system.rb:2
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/writer/workbook.rb:6
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/writer.rb:1
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/spreadsheet-0.6.4.1/lib/spreadsheet/excel/workbook.rb:3
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/sds/.rvm/gems/ruby-1.8.7-p248/gems/spreadsheet-0.6.4.1/lib/spreadsheet.rb:27
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Users/sds/.rvm/rubies/ruby-1.8.7-p248/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'

**Comment by jeremyevans** [comment]
As you can see from the backtrace, the error comes from ruby-ole, which is already mentioned as being incompatible in the README.

**Comment by remigijusj** [comment]
In case you don't mind patching installed gems, here is the fix:
http://gist.github.com/590217

**Comment by sdsykes** [comment]
@jeremyevans: so it is in the readme, thanks.  Is this permanently wontfix?  It's a bit of a dealbreaker for me.
@remigijusj: thanks for the patch, I'll consider doing that.

**Comment by jeremyevans** [comment]
It's not something that can be fixed.  Using allocate when the object is backed by a C data structure and is immutable after creation just can't work.  Really, the ruby-ole gem needs to be modified so it doesn't use allocate.

**Comment by sr3d** [comment]
There's a much cleaner, and unobtrusive work around to this issue, which I wrote up in my blog:

http://alexle.net/archives/310

remigijusj:  thanks for the patch!

**Comment by aquasync** [comment]
This has been fixed in the latest version of ruby-ole to use new! (with new0 fallback). Thanks for this library - the performance of the standard date class is abysmal (which is why the FileTime class is futzing around with its own julian-day calc in the first place).

One other incompatibility I ran into when making the tests pass though was that operations don't preserve subclassing. Eg regular DateTime#+ will keep the derived class, but the home run version doesn't. Would it be possible to do the equivalent of self.class.new in the code?

**Comment by jeremyevans** [comment]
I'm sure it's possible.  I didn't really think about that, and hard coding the class constant in the C code is fastest, so that's the route I took.  I'll look into this issue, but it's probably going to require changes in many places

Don't forget to push the new ruby-ole gem to rubygems.org, it still has 1.2.10.1 as the latest version.

**Comment by jeremyevans** [comment]
I just pushed some commits and a new gem version (0.9.4) that makes home_run return subclass instances if you call methods on a subclass or subclass instance.

**Comment by aquasync** [comment]
Yeah thanks I forgot about that - still used to pushing to rubyforge.

**Comment by aquasync** [comment]
Awesome - just checked out the new version and it works great. I'll remove my work around in the future.

**Comment by sdsykes** [comment]
Thanks aquasync / jeremy, great response, very happy this is resolved.
