### ISSUE TITLE
incompatibility with runt

### ISSUE THREAD

**Issue by clifton** [jeremyevans/home_run#19]
Runt is a temporal expression library that I use for generating dates on recurring events. It tries to access instance variables in the Date class that are not used by home_run (e.g. @ajd). 

I may fork Runt and patch it to work with home_run, but for the mean time would you mind adding it to the incompatibility list? Thanks!

http://runt.rubyforge.org/

**Comment by jeremyevans** [comment]
Add Runt to the incompatibilities section of the README (Closed by fa65f9d9e7897e6e3b54b9cf95a9549aa8f4764f)

Thanks to clifton for reporting this issue.
