### ISSUE TITLE
Allow use as a gem

### ISSUE THREAD

**Issue by jamie** [jeremyevans/home_run#2]
I would really like to be able to just

```
require 'home_run'
```

and have it undefine the existing Date/DateTime classes and then require its own. Specifically, this would make it usable on Heroku.

**Comment by jeremyevans** [comment]
Fixed: http://github.com/jeremyevans/home_run/commit/05b0e8d4b46f132b830520cb857e813fd7607db5

**Comment by jamie** [comment]
Awesome, thanks.
