### ISSUE TITLE
ruby-ole gem compatability? "uninitialized constant Ole::Types::FileTime::ITALY (NameError)"

### ISSUE THREAD

**Issue by dmix** [jeremyevans/home_run#22]
I'm getting the following error when I start my rails server:

/Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types/base.rb:78:in `new': uninitialized constant Ole::Types::FileTime::ITALY (NameError)
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types/base.rb:89:in`class:FileTime'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types/base.rb:60:in `<module:Types>'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types/base.rb:15:in`module:Ole'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types/base.rb:8:in `<top (required)>'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/types.rb:1:in`<top (required)>'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/storage/base.rb:6:in `<top (required)>'
    from /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/ruby-ole-1.2.11.1/lib/ole/storage.rb:1:in`<top (required)>'

When I remove the ruby-ole gem from Gemfile or uninstall home_run it works fine.

**Comment by jeremyevans** [comment]
Weird, I can't see any reason why it wouldn't work.  DateTime::ITALY is definitely defined by home_run.

Are you using the latest release of home_run?  Did you use home_run --install?  Is the situation any different if you run "home_run rails server"?  Do you get the error if you just do "irb -r ruby-ole" from the command line?

**Comment by dmix** [comment]
After reinstalling the gem, I'm no longer getting that error (likely had an old version installed).

But I am getting a new error that I haven't been able to resolve.

  /Users/dmix/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.5/lib/active_support/railtie.rb:54:in `block in class:Railtie': Value assigned to config.time_zone not recognized.Run "rake -D time" for a list of tasks for finding appropriate time zone names. (RuntimeError)

In my application.rb I defined the time zone as UTC, so I'm not sure why its erroring.

  config.time_zone = 'UTC'

**Comment by jeremyevans** [comment]
Can you get a full backtrace?  Does this problem only occur when home_run is used?  Looking at the active_support code, it seems unlikely that this problem could be caused by home_run.

**Comment by dmix** [comment]
Here's a full backtrace: https://gist.github.com/851349

If I do "home_run --uninstall" I no longer get this error.

**Comment by jeremyevans** [comment]
I can't replicate this:

```
$ rails c
Loading development environment (Rails 3.0.5)
irb(main):001:0> Rails::Application.config.time_zone = 'UTC'
=> "UTC"
irb(main):002:0> $LOADED_FEATURES.grep /date_ext/
=> ["date_ext.so"]
```

**Comment by dmix** [comment]
right, I've dug around the code quite a bit and can't figure it out.

closing ticket since its not repeatable.
