### ISSUE TITLE
Date range #cover? doesn't work as expected after requiring 'home_run'

### ISSUE THREAD

**Issue by maca** [jeremyevans/home_run#23]
ruby-1.9.2-p0 > require 'date'
 => true 
ruby-1.9.2-p0 >  r = (Date.civil(2010, 12, 1)..Date.civil(2010, 12, 31))
 => #<Date: 2010-12-01 (4911063/2,0,2299161)>..#<Date: 2010-12-31 (4911123/2,0,2299161)> 
ruby-1.9.2-p0 > r.cover? DateTime.civil(2010,12,7,15,0)
 => true 
ruby-1.9.2-p0 > require 'home_run'
 => true 
ruby-1.9.2-p0 > r.cover? DateTime.civil(2010,12,7,15,0)
 => false

**Comment by jeremyevans** [comment]
This only fails because you are mixing stdlib objects with home_run objects.  You shouldn't do that.  You need to require home_run before building the date range, either by using home_run --install or home_run ruby:

```
$ home_run19 ruby19 -e "p (Date.civil(2010, 12, 1)..Date.civil(2010, 12, 31)).cover? DateTime.civil(2010,12,7,15,0)"
true
```
