### ISSUE TITLE
Rails Time operations don't work

### ISSUE THREAD

**Issue by wxmn** [jeremyevans/home_run#31]
Using Rails 3.0.9, Ruby 1.9.2-p180, and HomeRun 1.0.3:

Basic natural language time operations like Time.now + 2.days result in this error:

NoMethodError: undefined method `advance' for #<Date 2011-07-15>
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/core_ext/time/calculations.rb:101:in`advance'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/duration.rb:91:in `block in sum'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/duration.rb:86:in`each'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/duration.rb:86:in `inject'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/duration.rb:86:in`sum'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/duration.rb:62:in `since'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.9/lib/active_support/core_ext/time/calculations.rb:245:in`plus_with_duration'
    from (irb):2
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.9/lib/rails/commands/console.rb:44:in `start'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.9/lib/rails/commands/console.rb:8:in`start'
    from /Users/wxmn/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.9/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by jeremyevans** [comment]
Works fine here:

```
$ rails c
Loading development environment (Rails 3.0.9)
irb(main):001:0> Time.now + 2.days
=> Sun Jul 17 08:03:25 -0700 2011
irb(main):002:0> Date::Format::STYLE
=> {:slash=>:mdy, :dot=>:ymd}
```

Make sure you have the following in your Gemfile:

```
gem 'home_run', :require=>'date'
```

or use the home_run command line utility:

```
home_run rails c
```

or:

```
home_run --install
rails c
```

Please let me know if that fixes it.  You could also try ruby-head, where stdlib Date is almost as fast as home_run.

**Comment by wxmn** [comment]
Ah, I needed to require 'date'. Sorry about the false alarm. Thanks!
