### ISSUE TITLE
Ran 'home_run install', specified home_run in Gemfile, and still no home_run

### ISSUE THREAD

**Issue by findchris** [jeremyevans/home_run#42]
Hi there.

I read around about many people having issues with home_run and bundler, and I think I tried all suggestions, without success.
```$ home_run --install
cp lib/date.rb /Users/chris/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8
mkdir -p /Users/chris/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/date
cp lib/date/format.rb /Users/chris/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/date
cp lib/date_ext.bundle /Users/chris/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/i686-darwin10.6.0

```

```

$ irb -rdate
ruby-1.8.7-p334 :001 > Date.today
 => #<Date 2012-02-09> 

```

```

$ rails console
ruby-1.8.7-p334 :001 > Date.today
 => Thu, 09 Feb 2012 

```

```

$ home_run rails console
ruby-1.8.7-p334 :001 > Date.today
 => Thu, 09 Feb 2012 

```

I have the following in my Gemfile:  `gem 'home_run', :require => 'date'`

Using Rails 3.0.10.

Would appreciate any help.

Thanks.
```

**Comment by jeremyevans** [comment]
Are you sure home_run isn't being loaded?  Date#inspect is overridden by ActiveSupport, so your examples are not an indication that home_run isn't being loaded.  The easiest way to check is to run this code `p Date::Format::STYLE`.  If it raises an exception, you aren't using home_run.

**Comment by findchris** [comment]
Result:
```ruby-1.8.7-p334 :002 > p Date::Format::STYLE
{:dot=>:ymd, :slash=>:mdy}

```

So I guess I'm using home_run then?

I did some profiling and noticed a lot of time spent in the `Date.valid_date_frags?` method, which is why I installed home_run.  After installing home_run, and running the profiler again, I still saw this method (sometimes, not always) taking up a large chunk of CPU time, so I thought that maybe home_run didn't install correctly.  Is this method still accessed when using home_run?

Thanks.
```

**Comment by jeremyevans** [comment]
Yes, you are using home_run.  However, home_run doesn't define the `Date.valid_date_frags?` method, so my guess is you are loading the stdlib date first, then home_run.  Not sure how that is happening, though.  What's the output of `$LOADED_FEATURES.grep(/date/)`

**Comment by findchris** [comment]
```ruby-1.8.7-p334 :002 > $LOADED_FEATURES.grep(/date/)
 => ["date_ext.bundle", "date.rb", "date/format.rb", "parsedate.rb", "active_support/file_update_checker.rb",
  "arel/update_manager.rb", "arel/nodes/update_statement.rb", "active_support/core_ext/date/zones.rb",
   "active_support/core_ext/date/calculations.rb", "active_support/core_ext/date_time/calculations.rb",
    "active_support/core_ext/date_time/conversions.rb", "active_support/core_ext/date/acts_like.rb",
     "active_support/core_ext/date/freeze.rb", "active_support/core_ext/date/conversions.rb",
      "active_support/core_ext/date_time/acts_like.rb", "active_support/core_ext/date_time/zones.rb",
       "tzinfo/time_or_datetime.rb", "active_model/validations/validates.rb", "action_view/helpers/date_helper.rb"] 

```
```

**Comment by jeremyevans** [comment]
Well, it looks like home_run was loaded and not the standard lib, but it's difficult to say exactly as ruby 1.8 doesn't put the full paths in LOADED_FEATURES.

Do you only get the `Date.valid_date_frags?` stuff when loading rails? Is `ruby -r date -e 'p Date.respond_to?(:valid_date_frags?, true)'` true or false?

**Comment by findchris** [comment]
Huh, this is returning `false`, and I am no longer able to get calls to `valid_date_frags?` during profiling.  I think I might have had an old Terminal session open that I finally restarted.

Anyway, I appreciate you taking the time to help me troubleshoot this, and thanks for creating home_run.  I'll re-open if this crops up again.
