### ISSUE TITLE
Segfault when Chef tries to install home_run

### ISSUE THREAD

**Issue by findchris** [jeremyevans/home_run#43]
This might be something you can't help with as it is quite specific, but we have Chef installing home_run on our servers (`gem install home_run; bundle exec home_run --install`) and a couple of servers failed with a segfault.  See below.

```
[Tue, 14 Feb 2012 15:21:44 -0800] DEBUG: Processing execute[install home run] on i-af084bca
[Tue, 14 Feb 2012 15:21:44 -0800] DEBUG: Executing bundle exec home_run --install
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: ---- Begin output of bundle exec home_run --install ----
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: STDOUT: 
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: STDERR: cp lib/date.rb /opt/ruby-enterprise/lib/ruby/site_ruby/1.8
mkdir -p /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/date
cp lib/date/format.rb /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/date
cp lib/date_ext.so /opt/ruby-enterprise/lib/ruby/site_ruby/1.8/x86_64-linux
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: ---- End output of bundle exec home_run --install ----
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: Ran bundle exec home_run --install returned 0
[Tue, 14 Feb 2012 15:21:45 -0800] INFO: Ran execute[install home run] successfully
[Tue, 14 Feb 2012 15:21:45 -0800] INFO: execute[install home run] sending create action to ruby_block[home_run_installed_flag] (immediate)
[Tue, 14 Feb 2012 15:21:45 -0800] DEBUG: Signing the request as i-af084bca
/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/date/format.rb:663: [BUG] Segmentation fault
ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2011.03

Aborted
```

I think what's happening is that the Chef process has its Ruby perhaps during execution.  If this is Chef specific and you aren't sure how to approach this, feel free to close the issue.  

Cheers.

**Comment by jeremyevans** [comment]
That segfault is in the ragel parser, which is the first reported case of it segfaulting.  Could you get me a C-level backtrace from gdb (`gdb ruby ruby.core` and run the `bt` command).

I also haven't had anyone reporting use of home run on REE, so it could be a general REE issue with home_run.

Is there a simpler way to reproduce what you are seeing (i.e. outside of Chef)?

**Comment by findchris** [comment]
Shoot.  Our auto-scaler spun down those EC2 instances, so gdb'ing is not currently an option.  I'll update when we can reproduce.

**Comment by findchris** [comment]
Hi again.

I have a machine spun upon that consistently reproduces this segfault.  It is definitely related to Chef somehow, as I can't reproduce via the command line.  My guess is that since Chef is running (a ruby process), and then home_run copies it's files over ruby's existing files (e.g. `/opt/ruby-enterprise/lib/ruby/site_ruby/1.8/date/format.rb`), ruby might not like that.  Is that possible?

**Comment by jeremyevans** [comment]
home_run doesn't copy files over existing files.  It does copy some files to site_ruby if you use --install, but the stdlib files that it takes precedence over don't live in site_ruby.

In any case, to debug this I'm going to need a gdb backtrace with the debug version of the gem (set DEBUG=1 environment variable when using gem install home_run to get the debug version).
