### ISSUE TITLE
fix for Ruby built with CALC_EXACT_MALLOC_SIZE

### ISSUE THREAD

**Issue by nocode** [jeremyevans/home_run#5]
I've pushed a trivial fix up to git://git.bogomips.org/home_run.git on the branch free-fix
Also viewable here: http://git.bogomips.org/cgit/home_run.git

**Comment by jeremyevans** [comment]
Applied: http://github.com/jeremyevans/home_run/commit/6616dafa26fa2473315f917b17c6cd73b0c79158

Thanks for your help Eric.

**Comment by jeremyevans** [comment]
Applied: http://github.com/jeremyevans/home_run/commit/6616dafa26fa2473315f917b17c6cd73b0c79158

Thanks for your help Eric.
