### ISSUE TITLE
uninitialized constant DateTime::Infinity

### ISSUE THREAD

**Issue by thoughtafter** [jeremyevans/home_run#50]
Looks like home_run 1.0.8 is incompatible with Rails 3.2.13 which references DateTime::Infinity in file /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/core_ext/date_time/calculations.rb line 141.

**Comment by jfcouture** [comment]
Just ran into the same bug.
I added 
class DateTime::Infinity; end

after require 'home_run' in boot.rb

It seems to work as a workaround for now.

**Comment by jeremyevans** [comment]
Thanks for the heads up!  I've released a new gem with this fix.

**Comment by jfcouture** [comment]
Wow! Thanks a lot for the quick fix and release!
