### ISSUE TITLE
not sure what's going on  here. Error page: uninitialized constant Date (NameError)

### ISSUE THREAD

**Issue by edwardt** [jeremyevans/home_run#51]
ured while starting up the preloader.
Error page:
uninitialized constant Date (NameError)
  /usr/local/share/gems/gems/date_ext-0.1.2/lib/weekday.rb:20:in `<top (required)>'
  /usr/local/share/gems/gems/date_ext-0.1.2/lib/date_ext.rb:2:in`require'
  /usr/local/share/gems/gems/date_ext-0.1.2/lib/date_ext.rb:2:in `<top (required)>'
  /usr/local/share/gems/gems/home_run-1.0.9/lib/date.rb:2:in`require'
  /usr/local/share/gems/gems/home_run-1.0.9/lib/date.rb:2:in `<top (required)>'
  /usr/local/share/gems/gems/home_run-1.0.9/lib/home_run.rb:4:in`load'
  /usr/local/share/gems/gems/home_run-1.0.9/lib/home_run.rb:4:in `<top (required)>'

**Comment by jeremyevans** [comment]
From your backtrace, it appears you have a separate gem called date_ext which conflicts with home_run's internal use of date_ext.so.  Fixing that will require hacking either home_run or date_ext to use a different name.  That's not a change I plan to make to home_run, as it is in maintenance mode.
