### ISSUE TITLE
Date#step without block given

### ISSUE THREAD

**Issue by remigijusj** [jeremyevans/home_run#6]
One more difference from standard library, not listed: 
<code>date.step(another_date)</code>  returns an instance of Enumerator in stdlib, but raises LocalJumpError in your version.
The same for Date#upto and Date.downto. 
Ruby version 1.9.1.

**Comment by jeremyevans** [comment]
I'll see how much work it would be to do this, as it is something I'd like to support.

**Comment by jeremyevans** [comment]
Thankfully, it was fairly easy to support: http://github.com/jeremyevans/home_run/commit/f2337319073a04f03bca2f14b69c9413a9a3e3f6
