### ISSUE TITLE
Encoding incompatibility

### ISSUE THREAD

**Issue by remigijusj** [jeremyevans/home_run#8]
On Ruby 1.9, Date#strftime returns strings with US-ASCII encoding, home_run's strftime gives ASCII-8BIT (binary). This can lead to errors when combining the result with strings encoded in UTF-8: 
"incompatible character encodings: UTF-8 and ASCII-8BIT".

**Comment by jeremyevans** [comment]
This is a bug and will be fixed.

**Comment by jeremyevans** [comment]
Return all strings in US-ASCII encoding on ruby 1.9 (Closed by e42fc0ba169e522764e4db2519f6707f77472dcd)
